build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - '%USERPROFILE%\.electron'


install:
  - ps: Install-Product node $env:node_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn build:prod
  - yarn e2e

on_failure:
  - 7z a e2e_test_logs.zip %APPVEYOR_BUILD_FOLDER%\*.log %APPVEYOR_BUILD_FOLDER%\errorShot-*.png
  - appveyor PushArtifact e2e_test_logs.zip

artifacts:
  - path: e2e_test_logs.zip
    name: e2eTestLogs
